### ISSUE TITLE
Create component(s) for toggling entity types to display 

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#155]
## Expected Behaviour

From invision 
<img width="527" alt="Screen Shot 2020-08-25 at 3 33 07 PM" src="https://user-images.githubusercontent.com/65875762/91119840-60429980-e6e8-11ea-9c56-f1cecd0cfb09.png">

Picking something small to try to get started with this sprint. I don't really know if we can distinguish between a Drug and Product yet - but can still probably create some buttons/toggles and get familiar with the app!

**Comment by mark-prins** [comment]
true re drug/product! What we have at the moment is 
- Product
- Form Category 
- Form 
- Unit of Use 

I think the distinction is between `Drug` and `Other` i.e. a pair of scissors. Which isn't a drug. 
In which case we should have `Drug` and `Other` instead of `Product`

anyway, that's detail and implementation. This should be about the 'chips' and the react component!

**Comment by wlthomson** [comment]
Agree with @mark-prins, good idea to keep the component as "dumb" as possible (i.e. no local state, just displays what is passed down as props). In this case, I think youd want a prop for the text and the boolean (e.g. `isActive`). Might need to add some icons from material for the "plus" and "tick" (can copy the existing icons).
