### ISSUE TITLE
Start SearchResults page

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/unified-codes#185]
## Expected Behaviour

Users should be able to find out more about medicinal products they find in the explorer (good way to show off the external codes too)

## Possible Solution

- Turn items in Explorer into link to a results page 
- On click, fire entity query requesting all children and properties of the selected medicinal_product
- Dump the data into a dummy results page (can deal with layout/styling later - I think already enough things for one issue)

**Comment by wlthomson** [comment]
Sounds good!

My thinking atm, for whatever it's worth:

- Since querying for a unique entity, can we just query by code (no need to specify `type` etc.?).
- How "deep" and "wide" do we want to go down the tree? I.e. do we want to get the children of children, the properties of properties, the properties of children etc. etc.?
- Are any backend changes needed, or can use the existing entity and entities queries. IMO it would be nice to keep the backend as non-coupled as possible, such that the back-end just exposes the entities etc. and the front-end gets what it needs depending on the context... do you guys agree or are you thinking towards a more RESTful-style with multiple queries to replicate "endpoints"?

**Comment by mark-prins** [comment]
> Since querying for a unique entity, can we just query by code?

agree! and the query is already there to support this, so we're all good.

> How "deep" and "wide" do we want to go down the tree? I.e. do we want to get the children of children, the properties of properties, the properties of children etc. etc.?

I'd say: minimum would be the level that we currently have as `medicinal_product` and the properties of it - which now includes WHO ATC, DDD, NZULM and will soon have NHIS link and UNSPC code.
Bonus points if we can show the forms, form categories and unit_of_uses that are under it, because that would be nice.

> Are any backend changes needed?

Nope

> My 2c: it would be nice to keep the backend as non-coupled as possible, such that the back-end just exposes the entities etc. and the front-end gets what it needs depending on the context... 

agree

**Comment by katherine-sussol** [comment]
👍  Agree with everything above - querying by code makes the most sense (particularly as later the explorer may potentially have non-medicinal products for people to click on...eyeing that 'Other' tab 👀 )
