### ISSUE TITLE
Narrow entity query search

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/unified-codes#259]
When searching for a matching item using mSupply, the current query which searches for 'contains' is too broad.
Add the ability to specify 'contains' or 'fuzzy' and default to 'starts with'

## Expected Behaviour
Searching for `Midazolam` should return products starting with `Mid` and not the current list, in which the top 25 doesn't include anything starting with 'M'

**Comment by wlthomson** [comment]
Is there a way we can avoid the term `fuzzy`? If we want to support multiple match patterns, can we update the terminology to be a bit clearer? E.g. `match="exact"`, `match="contains"`, `match="begin"`, or something like that? Also, is there a reason behind the logic for defaulting to `"contains"` rather than `"exact"`, i.e. should we try to minimise redundant results by defaulting to `"exact"`?

**Comment by mark-prins** [comment]
@wlthomson yes! to all of the above.
let's not `fuzzy`
