### ISSUE TITLE
Return properties of parent

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/unified-codes#276]
For entities at the `unit_of_use` level, some properties should be sourced from the parent not from the current node.
These are
- WHO EML categorisation
- RxCUID when used for interactions

## Expected Behaviour
When searching in mSupply for the product `Amoxicillin 250mg capsule` the property `who_eml` should come from the parent product `Amoxicillin` 

When searching for `Ampicillin 125mg/5mL oral liquid` the `code_rxnav` should be sourced from the parent, returning `733` - currently no interactions are returned.

Suggest prioritising property values: providing the immediate properties if specified, and reverting to parent properties if not. Only for the two properties specified though.

## Current Behaviour
Currently the WHO EML value is replicated at the `unit_of_use` level which avoids the problem. with the data changes this will become a problem and the EML property won't be returned for an entity.

**Comment by wlthomson** [comment]
I think the best way to do this as we move forward is to more directly expose the dgraph graph via graphql. That way the user can more explicitly request the info they want (which is kind of the whole deal with gql!). It requires a bit more knowledge on the users part (so we will need to document clearly our hiearchy and where the external links are), but I think it's by far the best way to go in terms of future proofing ourselves against client demands for xyz functionality.  Luckily due to graphql, we don't need to make query decisions based on what we think the user wants (like we would if using REST in this situation). 

@mark-prins @katherine-sussol Does that make sense? Agreement or no?

Does that make sense?

**Comment by mark-prins** [comment]
@wlthomson oh. you won't like this PR then 🤣 

I've gone with a specific implementation; I didn't see how to handle interactions when using the parent product RxCUID or how to request a product property of a specific type if the current entity doesn't have that prop.

**Comment by wlthomson** [comment]
> @wlthomson oh. you won't like this PR then 🤣
> 
> I've gone with a specific implementation; I didn't see how to handle interactions when using the parent product RxCUID or how to request a product property of a specific type if the current entity doesn't have that prop.

No worries, can always iterate (and I may not necessarily be thinking correctly anyways!).
