### ISSUE TITLE
Add visual indication of ** wildcard?

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/unified-codes#396]
## Expected Behaviour

In a [support ticket](https://support.msupply.org.nz/cerb6/profiles/ticket/TH-5195-TJ) Lauren (CHAI, Laos) asks whether you can search for an item that contains a phrase. 
![image](https://user-images.githubusercontent.com/29744386/118465740-4a817280-b756-11eb-9bc4-13c362af2b22.png)

Ideally we could later add a toggle or some way of changing this in the UI, but until then, do you think it could be useful to have some helper text indicating how it works?

## Current Behaviour

No indication of how to search for "includes x" rather than "starts with x"

**Comment by katherine-sussol** [comment]
Hmm thinking of something like:
![image](https://user-images.githubusercontent.com/65875762/119279831-4e475480-bc82-11eb-8784-f0d27fa347d1.png)

or 

![image](https://user-images.githubusercontent.com/65875762/119279894-99616780-bc82-11eb-84a9-cedf4774c179.png)

**Comment by mark-prins** [comment]
I like that - but I worry that it is more useful for developers and 'power users'
Do normal people search using wildcard indicators?

If that was in place, there would have to be more information - telling people what the asterisk means.
I would go with a more clumsy and failsafe approach
Either
- open out the search, so that is always searches with wildcards ( probably will return too many results )
- have a checkbox or other UI element to enable the full search and default to 'starts with' ( the old site functionality )

**Comment by katherine-sussol** [comment]
It sounds like some people do use `*`(I think it's really an unintended feature because the search string just gets chucked straight into a regex where it just happens to work, Rowena found it with her extensive testing 🤣 ). Most useful I think for combination drugs where users want to find all items that contain a particular drug (e.g. *lami will give Abacavir/Lamivudine)

I do like the UI element idea though (just wary of changing _tooo_ much haha), maybe radio buttons under the text input with `startsWith` and `contains` options?

**Comment by DhanyaHerath** [comment]
I promised Craig this set of work would take under a week :P How long would radio buttons take to implement?
Or could the "eg" text be changed to be `e.g. amoxicillin, amox, or *mox to search for items containing "mox"` or is that too clunky...? (I like the first option from [this comment](https://github.com/openmsupply/unified-codes/issues/396#issuecomment-846642008) by the way, I think it looks nicer!)

**Comment by katherine-sussol** [comment]
😆  probably a couple of days to do radio buttons? I optimistically want to say less but I think I am not that fast yet :P

I think the longer text version is much clearer, although once the screen width gets below about 1030px it starts to get cut off a bit, maybe this is fine? 
![image](https://user-images.githubusercontent.com/65875762/119281775-14c71700-bc8b-11eb-8d0e-baa2b1048193.png)

**Comment by mark-prins** [comment]
Too much?

![Screen Shot 2021-05-24 at 12 35 53 PM](https://user-images.githubusercontent.com/9192912/119282146-9ff4dc80-bc8c-11eb-917a-1eeda00cc39a.png)
