### ISSUE TITLE
Backend authorisation logic

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/unified-codes#66]
Need to authenticate users against an authentication store and be able to limit actions in dgraph, such as limiting mutations to specific roles.

## Expected Behavior
Should be able to restrict access to part of the web application to authenticated users. No requirement initially to have fine grained permissions, this will come later.

**Comment by mark-prins** [comment]
Looking at doing this:
- using keycloak as the authentication server and bundling this into the docker container
- configure authorisation in dgraph to use keycloak: add public key so that dgraph will accept JWT
- create realm in keycloack; configure ADMIN role
- implement `@auth` directive to accept mutations only when user has ADMIN role
- generate JWT and test

**Comment by wlthomson** [comment]
@mark-prins Sounds good! I haven't used `keycloak` before so will leave questions for the next sprint meeting!

**Comment by wlthomson** [comment]
@mark-prins Sounds good! I haven't used keycloak (assuming it's [this](https://www.keycloak.org/)?) before so will leave questions for the next sprint meeting!
